/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DistanceUnit = IDL.Variant({
  'miles' : IDL.Null,
  'meters' : IDL.Null,
  'kilometers' : IDL.Null,
});
export const RunLog = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'unit' : DistanceUnit,
  'user' : IDL.Principal,
  'distance' : IDL.Opt(IDL.Float64),
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'timeMinutes' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Achievement = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'unlockedDate' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'displayName' : IDL.Opt(IDL.Text) });
export const Goal = IDL.Record({
  'createdAt' : IDL.Int,
  'unit' : DistanceUnit,
  'targetTimeMinutes' : IDL.Float64,
  'targetDistance' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRunLog' : IDL.Func([RunLog], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeGoal' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'achievements' : IDL.Vec(Achievement) })],
      [],
    ),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'getAchievements' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(Achievement)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getMotivationMessage' : IDL.Func([], [IDL.Text], ['query']),
  'getRunLogs' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(RunLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDailyGoal' : IDL.Func([Goal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DistanceUnit = IDL.Variant({
    'miles' : IDL.Null,
    'meters' : IDL.Null,
    'kilometers' : IDL.Null,
  });
  const RunLog = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'unit' : DistanceUnit,
    'user' : IDL.Principal,
    'distance' : IDL.Opt(IDL.Float64),
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'timeMinutes' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Achievement = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'unlockedDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'displayName' : IDL.Opt(IDL.Text) });
  const Goal = IDL.Record({
    'createdAt' : IDL.Int,
    'unit' : DistanceUnit,
    'targetTimeMinutes' : IDL.Float64,
    'targetDistance' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRunLog' : IDL.Func([RunLog], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeGoal' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'achievements' : IDL.Vec(Achievement) })],
        [],
      ),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'getAchievements' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Achievement)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getMotivationMessage' : IDL.Func([], [IDL.Text], ['query']),
    'getRunLogs' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(RunLog)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDailyGoal' : IDL.Func([Goal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };