/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'unlockedDate' : bigint,
}
export type DistanceUnit = { 'miles' : null } |
  { 'meters' : null } |
  { 'kilometers' : null };
export interface Goal {
  'createdAt' : bigint,
  'unit' : DistanceUnit,
  'targetTimeMinutes' : number,
  'targetDistance' : [] | [number],
}
export interface RunLog {
  'id' : string,
  'createdAt' : bigint,
  'unit' : DistanceUnit,
  'user' : Principal,
  'distance' : [] | [number],
  'notes' : [] | [string],
  'timestamp' : bigint,
  'timeMinutes' : number,
}
export interface UserProfile { 'displayName' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRunLog' : ActorMethod<[RunLog], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeGoal' : ActorMethod<
    [string],
    { 'achievements' : Array<Achievement> }
  >,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'getAchievements' : ActorMethod<[[] | [bigint]], Array<Achievement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getMotivationMessage' : ActorMethod<[], string>,
  'getRunLogs' : ActorMethod<[[] | [bigint]], Array<RunLog>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailyGoal' : ActorMethod<[Goal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];